services:
  backend:
    build:
      context: ./backend
      args:
          - MODE=showcase
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/venv

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
